### PR TITLE
Frontend Test Environment

### PR DESCRIPTION
**Pull request by HadiAlizade77**

### CODE REVIEW

**Comment by HadiAlizade77** [comment]
###  **Happy Testing**

needs npm i -f

**Comment by HadiAlizade77** [comment]
https://react.dev/blog/2022/03/08/react-18-upgrade-guide

**Comment by HadiAlizade77** [comment]
ezgif-2-5ccc25c692

**Review by bariserol761 — APPROVED** [review]
lgtm

**Review by mervenuryazanel — APPROVED** [review]

**Pull request merged**
